[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
path = "src/lib.rs"
tests = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
